# Generated by Django 5.2.1 on 2025-11-14 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('costs_fee', '0001_initial'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traksions',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.ordermodel'),
        ),
    ]
