# Generated by Django 5.2.1 on 2025-11-19 06:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costs_fee', '0002_initial'),
        ('reservations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Traksions',
            new_name='Transactions',
        ),
    ]
