# Generated by Django 5.2.1 on 2025-11-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs_fee', '0003_rename_traksions_transactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costfeesite',
            name='types',
        ),
        migrations.AddField(
            model_name='costfeesite',
            name='title',
            field=models.CharField(blank=True, default='هزینه ارسال', max_length=20, null=True),
        ),
    ]
