# Generated by Django 5.2.1 on 2025-12-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs_fee', '0004_remove_costfeesite_types_costfeesite_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costfeesite',
            name='is_percent',
            field=models.BooleanField(default=False, verbose_name='درصدی است'),
        ),
        migrations.AlterField(
            model_name='costfeesite',
            name='title',
            field=models.CharField(blank=True, default='هزینه ارسال', max_length=20, null=True, unique=True),
        ),
    ]
