# Generated by Django 5.2.1 on 2025-12-14 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs_fee', '0005_alter_costfeesite_is_percent_alter_costfeesite_title'),
        ('reservations', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteCostFeeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cost_fee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='costs_fee.costfeesite')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.ordermodel')),
            ],
        ),
        migrations.DeleteModel(
            name='Transactions',
        ),
    ]
