# Generated by Django 5.2.1 on 2025-11-14 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollaboratorActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('ADD', 'Add'), ('REMOVE', 'Remove'), ('EDIT', 'Edit')], max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('activity_id', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShopCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_see_products', models.BooleanField(default=False)),
                ('can_add_product', models.BooleanField(default=False)),
                ('can_delete_product', models.BooleanField(default=False)),
                ('can_edit_product', models.BooleanField(default=False)),
                ('can_see_comments_and_questions', models.BooleanField(default=False)),
                ('can_response_questions', models.BooleanField(default=False)),
                ('can_remove_comments', models.BooleanField(default=False)),
                ('can_see_coupons', models.BooleanField(default=False)),
                ('can_edit_coupon', models.BooleanField(default=False)),
                ('can_add_coupon', models.BooleanField(default=False)),
                ('can_remove_coupon', models.BooleanField(default=False)),
                ('can_see_orders', models.BooleanField(default=False)),
                ('can_edit_orders', models.BooleanField(default=False)),
                ('can_see_collaborators', models.BooleanField(default=False)),
                ('can_edit_collaborators', models.BooleanField(default=False)),
                ('can_add_collaborators', models.BooleanField(default=False)),
                ('can_remove_collaborators', models.BooleanField(default=False)),
                ('gallery_all_permissions', models.BooleanField(default=False)),
                ('story_all_permissions', models.BooleanField(default=False)),
                ('product_video_permissions', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
