# Generated by Django 5.2.1 on 2025-11-14 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accaunts', '0002_initial'),
        ('collaborator', '0001_initial'),
        ('sellers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboratoractivity',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellers.shop'),
        ),
        migrations.AddField(
            model_name='shopcollaborator',
            name='national_id_auth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accaunts.nationalidauthentication'),
        ),
        migrations.AddField(
            model_name='shopcollaborator',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='sellers.shop'),
        ),
        migrations.AddField(
            model_name='shopcollaborator',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shopcollaborator',
            name='user_authentication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accaunts.userauthentication'),
        ),
        migrations.AddField(
            model_name='collaboratoractivity',
            name='shop_collaborator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collaborator.shopcollaborator'),
        ),
        migrations.AlterUniqueTogether(
            name='shopcollaborator',
            unique_together={('shop', 'user')},
        ),
    ]
