# Generated by Django 5.2.1 on 2025-11-17 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accaunts', '0002_initial'),
        ('collaborator', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcollaborator',
            name='national_id_auth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accaunts.nationalidauthentication'),
        ),
    ]
