# Generated by Django 5.2.1 on 2025-11-17 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborator', '0003_alter_shopcollaborator_national_id_auth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopcollaborator',
            name='national_id_auth',
        ),
    ]
