# Generated by Django 5.2.1 on 2025-11-14 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accaunts', '0001_initial'),
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_seller', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('national_id_auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accaunts.nationalidauthentication')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_authentication', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accaunts.userauthentication')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_shop', models.CharField(max_length=26)),
                ('description', models.CharField(max_length=120)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media/shop_logo')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='media/banner')),
                ('reported', models.BooleanField(default=False)),
                ('active', models.BooleanField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='sellers.seller')),
            ],
        ),
        migrations.CreateModel(
            name='ShopRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rateing', models.IntegerField()),
                ('reserv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.reservation')),
            ],
        ),
    ]
