# Generated by Django 5.2.1 on 2025-11-14 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Citys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='ProvinceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=40)),
                ('phone', models.CharField(max_length=11)),
                ('address', models.TextField()),
                ('paid', models.BooleanField(default=False)),
                ('postaddress', models.CharField(max_length=20)),
                ('tracking_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='کد رهگیری')),
                ('total_price', models.IntegerField()),
                ('payment_method', models.CharField(choices=[('WALLET', 'WALLET'), ('ZARRINPAL', 'ZARRINPAL')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.citys')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.provincecategory')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('totalprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preparation', models.BooleanField(default=False)),
                ('sent_to_post', models.BooleanField(default=False)),
                ('post_delivery', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('canceled', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('payment_method', models.CharField(blank=True, choices=[('WALLET', 'WALLET'), ('ZARRINPAL', 'ZARRINPAL')], max_length=20, null=True)),
                ('tracking_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='کد رهگیری')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.ordermodel', verbose_name='سفارش')),
            ],
        ),
    ]
