# Generated by Django 5.2.1 on 2025-11-14 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
        ('sellers', '0001_initial'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='shop.products'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellers.shop'),
        ),
    ]
