# Generated by Django 5.2.1 on 2025-11-14 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('charts', '0001_initial'),
        ('sellers', '0001_initial'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyprofit',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charts_monthlyprofits', to='sellers.shop'),
        ),
        migrations.AddField(
            model_name='productpricehistory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='shop.products'),
        ),
        migrations.AddField(
            model_name='productpricehistory',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellers.shop'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlyprofit',
            unique_together={('shop', 'year', 'month')},
        ),
        migrations.AlterUniqueTogether(
            name='productpricehistory',
            unique_together={('product', 'shop', 'date')},
        ),
    ]
