# Generated by Django 5.2.1 on 2025-11-14 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accaunts', '0001_initial'),
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userauthentication',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.citys'),
        ),
        migrations.AddField(
            model_name='userauthentication',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.provincecategory'),
        ),
        migrations.AddField(
            model_name='userauthentication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nationalidauthentication',
            name='user_authentication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accaunts.userauthentication'),
        ),
    ]
