# Generated by Django 5.2.1 on 2025-11-14 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sellers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/brand_images')),
                ('description', models.CharField(blank=True, max_length=70, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('display_mode', models.CharField(blank=True, choices=[('circle_card', 'circle_card'), ('default', 'default'), ('3d_card-(image - icon)', '3d_card-(image - icon)'), ('circle_card_raw_photo', 'circle_card_raw_photo'), ('list', 'list'), ('luxery_cart1-(image)', 'luxery_cart1-(image)'), ('luxery_cart2-(image)', 'luxery_cart2-(image)')], max_length=50, null=True)),
                ('image_page', models.ImageField(blank=True, null=True, upload_to='media/image_page')),
                ('backgrounds', models.CharField(blank=True, choices=[('blur', 'blur'), ('gradient', 'gradient'), ('dark', 'dark'), ('neon', 'neon')], max_length=50, null=True)),
                ('flex_row', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=50, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی گروهی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای گروهی',
            },
        ),
        migrations.CreateModel(
            name='ColorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color_grb', models.CharField(blank=True, default='#', max_length=70, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetaKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('icon', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuperCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='media/product_category_images')),
                ('image_page', models.ImageField(upload_to='media/product_category_images')),
                ('short_des', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی اصلی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای اصلی',
            },
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('image', models.ImageField(upload_to='media/product_category_images')),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('short_des', models.CharField(blank=True, max_length=50, null=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='main_categories', to='shop.category')),
                ('super_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_categories', to='shop.supercategory')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی میانی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای میانی',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='نام  ')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='media/product_images', verbose_name='1  575x575-عکس')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('sell_price', models.IntegerField(blank=True, null=True)),
                ('description_seo', models.CharField(blank=True, max_length=80, null=True, verbose_name='توضیحات سئو سایت')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('qunat', models.IntegerField(blank=True, null=True, verbose_name='تعداد موجود ')),
                ('is_sellprice', models.BooleanField(default=False, verbose_name='ایجاد تخفیف ویزه')),
                ('spessial', models.BooleanField(default=False, verbose_name='ایجاد محصول ویزه')),
                ('views', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('have', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.brandcategory')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.colorcategory')),
                ('like', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL)),
                ('main_cattegory', models.ManyToManyField(to='shop.maincategory')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellers.shop')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.supercategory')),
            ],
            options={
                'verbose_name': ' محصولات',
                'verbose_name_plural': 'همه محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductKeyValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
                ('is_image', models.BooleanField(default=False)),
                ('image2', models.ImageField(blank=True, max_length=1000, null=True, upload_to='media/product_imgs', verbose_name='2  575x575-عکس')),
                ('key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.productdetakeys')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='shop.products')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=320, verbose_name='متن')),
                ('rating', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='shop.products', verbose_name='محصول مورد نظر')),
            ],
        ),
        migrations.AddField(
            model_name='productdetakeys',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.supercategory'),
        ),
    ]
