# Generated by Django 5.2.1 on 2025-12-06 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productkeyvalues',
            name='image2',
        ),
    ]
