# Generated by Django 5.2.1 on 2025-12-14 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_productkeyvalues_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productkeyvalues',
            name='is_image',
        ),
    ]
