# Generated by Django 5.2.1 on 2025-12-17 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_productkeyvalues_is_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='backgrounds',
        ),
        migrations.RemoveField(
            model_name='category',
            name='display_mode',
        ),
        migrations.RemoveField(
            model_name='category',
            name='flex_row',
        ),
    ]
