# Generated by Django 5.2.1 on 2025-12-17 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_category_backgrounds_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image_page',
        ),
        migrations.RemoveField(
            model_name='supercategory',
            name='image_page',
        ),
    ]
