# Generated by Django 5.2.1 on 2025-11-14 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accaunts', '0001_initial'),
        ('question_response', '0001_initial'),
        ('tiketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('user_message', models.BooleanField(default=False)),
                ('supporter_message', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('responsed', models.BooleanField(default=False)),
                ('created', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ChatView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.BooleanField(default=False)),
                ('chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supporter.chatmessages')),
            ],
        ),
        migrations.AddField(
            model_name='chatmessages',
            name='chat_view',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporter.chatview'),
        ),
        migrations.CreateModel(
            name='Supporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('nation_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accaunts.nationalidauthentication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accaunts.userauthentication')),
            ],
        ),
        migrations.AddField(
            model_name='chatmessages',
            name='suport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suport', to='supporter.supporter'),
        ),
        migrations.CreateModel(
            name='SupporterActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg', models.IntegerField(default=0)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('chat_views', models.ManyToManyField(blank=True, to='supporter.chatview')),
                ('messages', models.ManyToManyField(blank=True, to='supporter.chatmessages')),
                ('response_tickets', models.ManyToManyField(blank=True, to='question_response.response')),
                ('supporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporter.supporter')),
                ('tickets', models.ManyToManyField(blank=True, to='tiketing.tikets')),
            ],
        ),
    ]
