# Generated by Django 5.2.1 on 2025-11-17 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessages',
            name='suport',
        ),
        migrations.RemoveField(
            model_name='supporteractivity',
            name='avg',
        ),
        migrations.AddField(
            model_name='chatmessages',
            name='supporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supporter', to='supporter.supporter'),
        ),
    ]
