# Generated by Django 5.2.1 on 2025-11-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporter', '0002_remove_chatmessages_suport_and_more'),
        ('tiketing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supporteractivity',
            name='response_tickets',
        ),
        migrations.AlterField(
            model_name='supporteractivity',
            name='tickets',
            field=models.ManyToManyField(blank=True, to='tiketing.responsetotiket'),
        ),
    ]
