# Generated by Django 5.2.1 on 2025-12-17 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accaunts', '0002_initial'),
        ('supporter', '0003_remove_supporteractivity_response_tickets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supporter',
            name='nation_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accaunts.nationalidauthentication'),
        ),
    ]
