# Generated by Django 5.2.1 on 2025-11-14 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gallery_products', '0001_initial'),
        ('sellers', '0001_initial'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryproducts',
            name='product',
            field=models.ManyToManyField(to='shop.products'),
        ),
        migrations.AddField(
            model_name='galleryproducts',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sellers.shop'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='gallery_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery_products.galleryproducts'),
        ),
    ]
