# Generated by Django 5.2.4 on 2025-08-31 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFaceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entred_password_at', models.DateTimeField(auto_created=True)),
                ('face_image', models.ImageField(upload_to='media/face_data')),
                ('password', models.CharField(max_length=200)),
                ('password_for', models.CharField(blank=True, choices=[('shops', 'shops'), ('seller_dashbord', 'seller_dashbord'), ('profile', 'profile'), ('wallet', 'wallet')], max_length=20, null=True)),
                ('default_lock', models.IntegerField(default=15)),
                ('is_entered', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
