# Generated by Django 5.2.1 on 2025-11-23 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsetotiket',
            name='response_for_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsed_tiket', to='tiketing.tikets'),
        ),
    ]
