# Generated by Django 5.2.1 on 2025-11-14 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgfor', models.CharField(choices=[('shop', 'shop'), ('authed_user', 'authed_user')], max_length=100000)),
                ('gender', models.CharField(blank=True, choices=[('MEN', 'MEN'), ('WOMEN', 'WOMEN')], null=True)),
                ('image', models.ImageField(upload_to='media/supporter_user_image')),
            ],
        ),
        migrations.CreateModel(
            name='MerchanteCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='SeoWebSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('shop', 'shop'), ('products', 'products'), ('category', 'category'), ('blogs', 'blogs')], max_length=100)),
                ('title', models.CharField(help_text='نام وب سایت | معرفی محصول.   مثال:  فهرست محصولات لپ\u200cتاپ، کامپیوتر و لوازم جانبی با بهترین کیفیت و قیمت.', max_length=65)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=90)),
                ('site_title', models.CharField(blank=True, default='Ala Kala', max_length=20, null=True)),
                ('persian_site_title', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('telegram_url', models.URLField(blank=True, null=True)),
                ('whatsapp_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('linkdn_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SymbolOfTrust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/symbol_of_trust_image')),
                ('url', models.URLField()),
                ('title', models.CharField(default='امنیت خرید شما، اولویت ماست', max_length=50)),
            ],
        ),
    ]
