# Generated by Django 5.2.1 on 2025-11-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteinfo', '0003_promotionalcardproduct_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionalproductsslide',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='promotionalproductsslide',
            name='name',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
