# Generated by Django 5.2.1 on 2025-12-10 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteinfo', '0004_promotionalproductsslide_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='media/web site favicon'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='site_title',
            field=models.CharField(blank=True, default='Alastra', max_length=20, null=True),
        ),
    ]
