# Generated by Django 5.2.1 on 2025-12-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteinfo', '0005_siteinfo_favicon_alter_siteinfo_site_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='media/web_favicon'),
        ),
    ]
