# Generated by Django 5.2.1 on 2025-12-15 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteinfo', '0006_alter_siteinfo_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='web_header',
            field=models.ImageField(blank=True, null=True, upload_to='media/web_header'),
        ),
    ]
