# Generated by Django 5.2.1 on 2025-12-15 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteinfo', '0007_siteinfo_web_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='web_header_style_class',
            field=models.CharField(blank=True, default='h-10 w-32', max_length=200, null=True),
        ),
    ]
