# Generated by Django 5.2.1 on 2025-12-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteinfo', '0008_siteinfo_web_header_style_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='web_header_style_class',
            field=models.CharField(blank=True, default='h-10 w-32', help_text='w=عرض. h=ارتفاع.', max_length=200, null=True),
        ),
    ]
