# Generated by Django 5.2.1 on 2025-12-20 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=400)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DemoVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='test/DemoVideos')),
            ],
        ),
        migrations.CreateModel(
            name='OgPowerFullSeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('des', models.TextField(max_length=4000)),
                ('keyword', models.TextField(max_length=4000)),
                ('url', models.URLField(max_length=2000)),
                ('image', models.ImageField(upload_to='test/OgPowerFullSeo')),
            ],
        ),
        migrations.CreateModel(
            name='PowerFullSeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('des', models.TextField(max_length=4000)),
                ('keyword', models.TextField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.URLField(max_length=2000)),
                ('name', models.CharField(max_length=200)),
                ('alt', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('url_domain', models.URLField()),
                ('image', models.ImageField(upload_to='test/Project_image')),
                ('desc', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('des', models.TextField(max_length=400)),
                ('file', models.FileField(upload_to='test/files')),
            ],
        ),
        migrations.CreateModel(
            name='DemoPhotoGraphs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='test/DemoPhotoGraphs')),
                ('url', models.URLField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adv.project')),
            ],
        ),
    ]
