# Generated by Django 5.2.1 on 2025-12-20 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demophotographs',
            name='alt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
