# Generated by Django 5.2.1 on 2025-12-21 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adv', '0002_demophotographs_alt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conactions',
            old_name='name',
            new_name='icon',
        ),
    ]
